{
    "identifier": "CVE-2017-2810",
    "summary": "An exploitable vulnerability exists in the Databook loading functionality of Tablib 0.11.4. A yaml loaded Databook can execute arbitrary python commands resulting in command execution. An attacker can insert python into loaded yaml to trigger this vulnerability.",
    "references": [
        {
            "url": "",
            "reference_id": "pyup.io-35731"
        }
    ],
    "vulnerable_packages": [
        "pkg:pypi/tablib@0.9.4",
        "pkg:pypi/tablib@0.9.11",
        "pkg:pypi/tablib@0.8.3",
        "pkg:pypi/tablib@0.9.9",
        "pkg:pypi/tablib@0.9.2",
        "pkg:pypi/tablib@0.11.2",
        "pkg:pypi/tablib@0.11.0",
        "pkg:pypi/tablib@0.10.0",
        "pkg:pypi/tablib@0.9.5",
        "pkg:pypi/tablib@0.8.1",
        "pkg:pypi/tablib@0.8.0",
        "pkg:pypi/tablib@0.9.6",
        "pkg:pypi/tablib@0.0.1",
        "pkg:pypi/tablib@0.9.10",
        "pkg:pypi/tablib@0.11.3",
        "pkg:pypi/tablib@0.9.8",
        "pkg:pypi/tablib@0.9.1",
        "pkg:pypi/tablib@0.11.1",
        "pkg:pypi/tablib@0.8.4",
        "pkg:pypi/tablib@0.9.0",
        "pkg:pypi/tablib@0.6.4",
        "pkg:pypi/tablib@0.6.1",
        "pkg:pypi/tablib@0.6.2",
        "pkg:pypi/tablib@0.7.0",
        "pkg:pypi/tablib@0.7.1",
        "pkg:pypi/tablib@0.8.2",
        "pkg:pypi/tablib@0.6.3",
        "pkg:pypi/tablib@0.9.3",
        "pkg:pypi/tablib@0.9.7"
    ],
    "resolved_packages": [
        "pkg:pypi/tablib@2.0.0",
        "pkg:pypi/tablib@0.11.4",
        "pkg:pypi/tablib@1.1.0",
        "pkg:pypi/tablib@0.14.0",
        "pkg:pypi/tablib@1.0.0",
        "pkg:pypi/tablib@0.12.1",
        "pkg:pypi/tablib@0.12.0",
        "pkg:pypi/tablib@0.13.0",
        "pkg:pypi/tablib@0.11.5"
    ]
}