{
    "identifier": "VULCODE-2020-09-26 12:51:22.754498",
    "summary": "Python-socketio 4.3.0 addresses potential websocket cross-origin attacks. See: <https://github.com/miguelgrinberg/python-engineio/issues/128>.",
    "references": [
        {
            "url": "",
            "reference_id": "pyup.io-37308"
        }
    ],
    "vulnerable_packages": [
        "pkg:pypi/python-socketio@1.7.7",
        "pkg:pypi/python-socketio@3.1.2",
        "pkg:pypi/python-socketio@2.1.1",
        "pkg:pypi/python-socketio@0.4.2",
        "pkg:pypi/python-socketio@1.1",
        "pkg:pypi/python-socketio@0.9.2",
        "pkg:pypi/python-socketio@4.0.0",
        "pkg:pypi/python-socketio@3.1.0",
        "pkg:pypi/python-socketio@0.3.0",
        "pkg:pypi/python-socketio@1.4.1",
        "pkg:pypi/python-socketio@1.4.4",
        "pkg:pypi/python-socketio@4.1.0",
        "pkg:pypi/python-socketio@1.2",
        "pkg:pypi/python-socketio@0.5.2",
        "pkg:pypi/python-socketio@1.4",
        "pkg:pypi/python-socketio@4.2.0",
        "pkg:pypi/python-socketio@1.6.1",
        "pkg:pypi/python-socketio@2.1.2",
        "pkg:pypi/python-socketio@1.6.2",
        "pkg:pypi/python-socketio@3.0.0",
        "pkg:pypi/python-socketio@0.4.1",
        "pkg:pypi/python-socketio@1.8.2",
        "pkg:pypi/python-socketio@3.0.1",
        "pkg:pypi/python-socketio@0.6.0",
        "pkg:pypi/python-socketio@2.1.0",
        "pkg:pypi/python-socketio@1.7.3",
        "pkg:pypi/python-socketio@1.7.4",
        "pkg:pypi/python-socketio@0.8.0",
        "pkg:pypi/python-socketio@1.7.1",
        "pkg:pypi/python-socketio@1.6.3",
        "pkg:pypi/python-socketio@1.7.5",
        "pkg:pypi/python-socketio@4.0.3",
        "pkg:pypi/python-socketio@0.2.0",
        "pkg:pypi/python-socketio@0.9.0",
        "pkg:pypi/python-socketio@1.8.3",
        "pkg:pypi/python-socketio@1.5.1",
        "pkg:pypi/python-socketio@0.7.0",
        "pkg:pypi/python-socketio@1.4.3",
        "pkg:pypi/python-socketio@3.1.1",
        "pkg:pypi/python-socketio@1.6.0",
        "pkg:pypi/python-socketio@2.0.0",
        "pkg:pypi/python-socketio@4.0.2",
        "pkg:pypi/python-socketio@0.1.0",
        "pkg:pypi/python-socketio@1.8.1",
        "pkg:pypi/python-socketio@1.8.4",
        "pkg:pypi/python-socketio@0.4.0",
        "pkg:pypi/python-socketio@1.3",
        "pkg:pypi/python-socketio@0.5.0",
        "pkg:pypi/python-socketio@0.8.2",
        "pkg:pypi/python-socketio@4.0.1",
        "pkg:pypi/python-socketio@0.8.1",
        "pkg:pypi/python-socketio@0.5.1",
        "pkg:pypi/python-socketio@1.7.2",
        "pkg:pypi/python-socketio@1.9.0",
        "pkg:pypi/python-socketio@1.7.6",
        "pkg:pypi/python-socketio@1.8.0",
        "pkg:pypi/python-socketio@1.4.2",
        "pkg:pypi/python-socketio@0.6.1",
        "pkg:pypi/python-socketio@0.9.1",
        "pkg:pypi/python-socketio@1.5.0",
        "pkg:pypi/python-socketio@4.2.1",
        "pkg:pypi/python-socketio@1.0",
        "pkg:pypi/python-socketio@1.7.0"
    ],
    "resolved_packages": [
        "pkg:pypi/python-socketio@4.6.0",
        "pkg:pypi/python-socketio@4.5.1",
        "pkg:pypi/python-socketio@4.3.0",
        "pkg:pypi/python-socketio@4.3.1",
        "pkg:pypi/python-socketio@4.4.0",
        "pkg:pypi/python-socketio@4.5.0"
    ]
}