{
    "identifier": "VULCODE-2020-09-26 12:46:33.182879",
    "summary": "Django-allauth 0.41.0 conforms to the general Django 3.0.1, 2.2.9, and 1.11.27 security release - see CVE-2019-19844 and https://www.djangoproject.com/weblog/2019/dec/18/security-releases/",
    "references": [
        {
            "url": "",
            "reference_id": "pyup.io-37664"
        }
    ],
    "vulnerable_packages": [
        "pkg:pypi/django-allauth@0.24.0",
        "pkg:pypi/django-allauth@0.3.0",
        "pkg:pypi/django-allauth@0.4.0",
        "pkg:pypi/django-allauth@0.10.0",
        "pkg:pypi/django-allauth@0.39.0",
        "pkg:pypi/django-allauth@0.15.0",
        "pkg:pypi/django-allauth@0.16.1",
        "pkg:pypi/django-allauth@0.13.0",
        "pkg:pypi/django-allauth@0.2.0",
        "pkg:pypi/django-allauth@0.36.0",
        "pkg:pypi/django-allauth@0.8.1",
        "pkg:pypi/django-allauth@0.40.0",
        "pkg:pypi/django-allauth@0.14.0",
        "pkg:pypi/django-allauth@0.12.0",
        "pkg:pypi/django-allauth@0.27.0",
        "pkg:pypi/django-allauth@0.8.2",
        "pkg:pypi/django-allauth@0.8.3",
        "pkg:pypi/django-allauth@0.37.1",
        "pkg:pypi/django-allauth@0.38.0",
        "pkg:pypi/django-allauth@0.23.0",
        "pkg:pypi/django-allauth@0.14.1",
        "pkg:pypi/django-allauth@0.26.1",
        "pkg:pypi/django-allauth@0.25.0",
        "pkg:pypi/django-allauth@0.35.0",
        "pkg:pypi/django-allauth@0.19.1",
        "pkg:pypi/django-allauth@0.31.0",
        "pkg:pypi/django-allauth@0.25.1",
        "pkg:pypi/django-allauth@0.1.0",
        "pkg:pypi/django-allauth@0.14.2",
        "pkg:pypi/django-allauth@0.21.0",
        "pkg:pypi/django-allauth@0.7.0",
        "pkg:pypi/django-allauth@0.37.0",
        "pkg:pypi/django-allauth@0.29.0",
        "pkg:pypi/django-allauth@0.17.0",
        "pkg:pypi/django-allauth@0.24.1",
        "pkg:pypi/django-allauth@0.26.0",
        "pkg:pypi/django-allauth@0.25.2",
        "pkg:pypi/django-allauth@0.9.0",
        "pkg:pypi/django-allauth@0.32.0",
        "pkg:pypi/django-allauth@0.11.0",
        "pkg:pypi/django-allauth@0.34.0",
        "pkg:pypi/django-allauth@0.20.0",
        "pkg:pypi/django-allauth@0.10.1",
        "pkg:pypi/django-allauth@0.11.1",
        "pkg:pypi/django-allauth@0.8.0",
        "pkg:pypi/django-allauth@0.39.1",
        "pkg:pypi/django-allauth@0.30.0",
        "pkg:pypi/django-allauth@0.6.0",
        "pkg:pypi/django-allauth@0.19.0",
        "pkg:pypi/django-allauth@0.22.0",
        "pkg:pypi/django-allauth@0.16.0",
        "pkg:pypi/django-allauth@0.5.0",
        "pkg:pypi/django-allauth@0.28.0",
        "pkg:pypi/django-allauth@0.33.0",
        "pkg:pypi/django-allauth@0.18.0"
    ],
    "resolved_packages": [
        "pkg:pypi/django-allauth@0.41.0",
        "pkg:pypi/django-allauth@0.42.0"
    ]
}