{
    "identifier": "VULCODE-2020-09-26 12:45:14.666519",
    "summary": "collective.js.datatables 4.1.1 updates Datatables to 1.10.11, due to a XSS vulnerability in 1.10.4.",
    "references": [
        {
            "url": "",
            "reference_id": "pyup.io-25659"
        }
    ],
    "vulnerable_packages": [
        "pkg:pypi/collective.js.datatables@1.9.2.1",
        "pkg:pypi/collective.js.datatables@1.8.0",
        "pkg:pypi/collective.js.datatables@1.9.2.2",
        "pkg:pypi/collective.js.datatables@1.9.2",
        "pkg:pypi/collective.js.datatables@1.7.4.3",
        "pkg:pypi/collective.js.datatables@1.8.0.1",
        "pkg:pypi/collective.js.datatables@1.8.0.2",
        "pkg:pypi/collective.js.datatables@1.7.4.1",
        "pkg:pypi/collective.js.datatables@1.9",
        "pkg:pypi/collective.js.datatables@1.9.3.1",
        "pkg:pypi/collective.js.datatables@3.1.10.4",
        "pkg:pypi/collective.js.datatables@3.1.10.5",
        "pkg:pypi/collective.js.datatables@2.0.1",
        "pkg:pypi/collective.js.datatables@2.0",
        "pkg:pypi/collective.js.datatables@1.9.2.3",
        "pkg:pypi/collective.js.datatables@1.7.4.2",
        "pkg:pypi/collective.js.datatables@1.9.1",
        "pkg:pypi/collective.js.datatables@1.7.5.1",
        "pkg:pypi/collective.js.datatables@4.0.0",
        "pkg:pypi/collective.js.datatables@1.7.5.2"
    ],
    "resolved_packages": [
        "pkg:pypi/collective.js.datatables@4.1.2",
        "pkg:pypi/collective.js.datatables@4.1.1"
    ]
}