{
    "identifier": "VULCODE-2020-09-26 12:45:00.852089",
    "summary": "cffconvert 1.0.3 updates requests from 2.18.4 to 2.20.0 (security bugfix)",
    "references": [
        {
            "url": "",
            "reference_id": "pyup.io-36623"
        }
    ],
    "vulnerable_packages": [
        "pkg:pypi/cffconvert@0.0.3",
        "pkg:pypi/cffconvert@1.0.0",
        "pkg:pypi/cffconvert@1.0.1",
        "pkg:pypi/cffconvert@0.0.4",
        "pkg:pypi/cffconvert@0.0.5",
        "pkg:pypi/cffconvert@1.0.2"
    ],
    "resolved_packages": [
        "pkg:pypi/cffconvert@1.2.0",
        "pkg:pypi/cffconvert@1.3.3",
        "pkg:pypi/cffconvert@1.0.4",
        "pkg:pypi/cffconvert@1.3.1",
        "pkg:pypi/cffconvert@1.0.3",
        "pkg:pypi/cffconvert@1.2.1",
        "pkg:pypi/cffconvert@1.3.2",
        "pkg:pypi/cffconvert@1.3.0",
        "pkg:pypi/cffconvert@1.1.0",
        "pkg:pypi/cffconvert@1.2.2"
    ]
}