{
    "identifier": "VULCODE-2020-09-26 12:53:11.990274",
    "summary": "trash-cli before 0.17.1.14 has a bug that causes trash-put to use $topdir/.Trash/UID trashcan even when it is not secure and $topdir/.Trash-UID should be used instead.",
    "references": [
        {
            "url": "",
            "reference_id": "pyup.io-34319"
        }
    ],
    "vulnerable_packages": [
        "pkg:pypi/trash-cli@0.12.4",
        "pkg:pypi/trash-cli@0.16.12.29",
        "pkg:pypi/trash-cli@0.16.12.25",
        "pkg:pypi/trash-cli@0.11.2",
        "pkg:pypi/trash-cli@0.12.6",
        "pkg:pypi/trash-cli@0.17.1.12",
        "pkg:pypi/trash-cli@0.2.1.dev-r81",
        "pkg:pypi/trash-cli@0.2.1.dev-r192",
        "pkg:pypi/trash-cli@0.2.1.dev-r79",
        "pkg:pypi/trash-cli@0.2.1.dev-r168",
        "pkg:pypi/trash-cli@0.2.1.dev-r143",
        "pkg:pypi/trash-cli@0.11.3-r315",
        "pkg:pypi/trash-cli@0.17.1.1",
        "pkg:pypi/trash-cli@0.11.0",
        "pkg:pypi/trash-cli@0.2.1.dev-r191",
        "pkg:pypi/trash-cli@0.2.1.dev-r141",
        "pkg:pypi/trash-cli@0.2.1.dev-r82",
        "pkg:pypi/trash-cli@0.2.1.dev-r153",
        "pkg:pypi/trash-cli@0.2.1.dev-r190",
        "pkg:pypi/trash-cli@0.16.12.28",
        "pkg:pypi/trash-cli@0.2.1.dev-r184",
        "pkg:pypi/trash-cli@0.11.1.2",
        "pkg:pypi/trash-cli@0.2.1.dev-r157",
        "pkg:pypi/trash-cli@0.12.9.14",
        "pkg:pypi/trash-cli@0.12.4.24",
        "pkg:pypi/trash-cli@0.11.0.dev-r215",
        "pkg:pypi/trash-cli@0.2.1.dev-r160",
        "pkg:pypi/trash-cli@0.2.1.dev-r142",
        "pkg:pypi/trash-cli@0.12.7",
        "pkg:pypi/trash-cli@0.16.12.26",
        "pkg:pypi/trash-cli@0.2.1.dev-r129",
        "pkg:pypi/trash-cli@0.11.0.dev-r199"
    ],
    "resolved_packages": [
        "pkg:pypi/trash-cli@0.17.1.14"
    ]
}