{
    "identifier": "VULCODE-2020-09-26 12:52:30.046499",
    "summary": "A security issue involving an improperly named channel logs was fixed in Sopel 4.4.0.",
    "references": [
        {
            "url": "",
            "reference_id": "pyup.io-26139"
        }
    ],
    "vulnerable_packages": [],
    "resolved_packages": [
        "pkg:pypi/sopel@6.1.1",
        "pkg:pypi/sopel@6.2.0",
        "pkg:pypi/sopel@6.6.7",
        "pkg:pypi/sopel@6.6.3",
        "pkg:pypi/sopel@7.0.6",
        "pkg:pypi/sopel@6.6.4",
        "pkg:pypi/sopel@6.0.0",
        "pkg:pypi/sopel@7.0.0rc1",
        "pkg:pypi/sopel@6.6.9",
        "pkg:pypi/sopel@7.0.4",
        "pkg:pypi/sopel@6.5.2",
        "pkg:pypi/sopel@6.5.0",
        "pkg:pypi/sopel@6.6.0",
        "pkg:pypi/sopel@6.0.0a4",
        "pkg:pypi/sopel@7.0.0rc2",
        "pkg:pypi/sopel@6.2.1",
        "pkg:pypi/sopel@6.6.8",
        "pkg:pypi/sopel@6.1.0",
        "pkg:pypi/sopel@6.0.0b0",
        "pkg:pypi/sopel@7.0.2",
        "pkg:pypi/sopel@7.0.1",
        "pkg:pypi/sopel@7.0.5",
        "pkg:pypi/sopel@6.5.3",
        "pkg:pypi/sopel@7.0.3",
        "pkg:pypi/sopel@6.5.1",
        "pkg:pypi/sopel@6.6.5",
        "pkg:pypi/sopel@6.3.1",
        "pkg:pypi/sopel@6.0.0a5",
        "pkg:pypi/sopel@7.0.0",
        "pkg:pypi/sopel@6.6.2",
        "pkg:pypi/sopel@6.6.6",
        "pkg:pypi/sopel@6.6.1",
        "pkg:pypi/sopel@6.4.0",
        "pkg:pypi/sopel@6.3.0"
    ]
}