{
    "identifier": "VULCODE-2020-09-26 12:51:11.033943",
    "summary": "pysandbox before 1.0.3 allows access to dict.__init__().",
    "references": [
        {
            "url": "",
            "reference_id": "pyup.io-26054"
        }
    ],
    "vulnerable_packages": [
        "pkg:pypi/pysandbox@1.0.0"
    ],
    "resolved_packages": []
}