{
    "identifier": "VULCODE-2020-09-26 12:51:00.520113",
    "summary": "pyoes 0.9.0 change: Libs updaten - security alert",
    "references": [
        {
            "url": "",
            "reference_id": "pyup.io-37254"
        }
    ],
    "vulnerable_packages": [
        "pkg:pypi/pyoes@0.4.2",
        "pkg:pypi/pyoes@0.3.3",
        "pkg:pypi/pyoes@0.4.0",
        "pkg:pypi/pyoes@0.2.1",
        "pkg:pypi/pyoes@0.4.3",
        "pkg:pypi/pyoes@0.4.8",
        "pkg:pypi/pyoes@0.6.0",
        "pkg:pypi/pyoes@0.4.7",
        "pkg:pypi/pyoes@0.3.1",
        "pkg:pypi/pyoes@0.3.0a0",
        "pkg:pypi/pyoes@0.4.4",
        "pkg:pypi/pyoes@0.5.0",
        "pkg:pypi/pyoes@0.3.0",
        "pkg:pypi/pyoes@0.7.0",
        "pkg:pypi/pyoes@0.4.5",
        "pkg:pypi/pyoes@0.8.0",
        "pkg:pypi/pyoes@0.4.6",
        "pkg:pypi/pyoes@0.3.2",
        "pkg:pypi/pyoes@0.4.1"
    ],
    "resolved_packages": [
        "pkg:pypi/pyoes@0.9.2",
        "pkg:pypi/pyoes@0.11.1",
        "pkg:pypi/pyoes@0.9.1",
        "pkg:pypi/pyoes@0.9.0",
        "pkg:pypi/pyoes@0.11.2",
        "pkg:pypi/pyoes@0.11.0",
        "pkg:pypi/pyoes@0.10.0"
    ]
}