{
    "identifier": "VULCODE-2020-09-26 12:49:18.712263",
    "summary": "mss before 2.0.18 has a undisclosed security issue.",
    "references": [
        {
            "url": "",
            "reference_id": "pyup.io-25898"
        }
    ],
    "vulnerable_packages": [
        "pkg:pypi/mss@0.0.8",
        "pkg:pypi/mss@0.1.1",
        "pkg:pypi/mss@1.0.2",
        "pkg:pypi/mss@0.0.4",
        "pkg:pypi/mss@0.0.6",
        "pkg:pypi/mss@1.0.0",
        "pkg:pypi/mss@0.0.3",
        "pkg:pypi/mss@0.1.0",
        "pkg:pypi/mss@0.0.5",
        "pkg:pypi/mss@2.0.0",
        "pkg:pypi/mss@0.0.7",
        "pkg:pypi/mss@0.0.2"
    ],
    "resolved_packages": [
        "pkg:pypi/mss@3.3.1",
        "pkg:pypi/mss@4.0.3",
        "pkg:pypi/mss@4.0.1",
        "pkg:pypi/mss@3.2.0",
        "pkg:pypi/mss@3.2.1",
        "pkg:pypi/mss@3.3.0",
        "pkg:pypi/mss@3.1.0",
        "pkg:pypi/mss@3.1.2",
        "pkg:pypi/mss@5.0.0",
        "pkg:pypi/mss@4.0.2",
        "pkg:pypi/mss@3.0.1",
        "pkg:pypi/mss@3.1.1",
        "pkg:pypi/mss@5.1.0",
        "pkg:pypi/mss@3.3.2",
        "pkg:pypi/mss@6.0.0",
        "pkg:pypi/mss@2.0.18",
        "pkg:pypi/mss@4.0.0",
        "pkg:pypi/mss@3.0.0",
        "pkg:pypi/mss@2.0.22"
    ]
}